name = "Vulcan"
uuid = "bfe7e8f3-634c-4759-86cf-c7631eccc6cf"
authors = ["Damir Akchurin <akchurinda@gmail.com>"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
OrderedCollections = "1.8.1"
Reexport = "1.2.2"
